from app.extensions import db


class Presence(db.Model):
    """One row = one user physically present in one room for one slot on
    one date. Generated by services/presence_builder.py from timetable +
    enrollment, never entered directly by a user."""

    __tablename__ = "presence"

    id = db.Column(db.BigInteger, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    room_id = db.Column(db.Integer, db.ForeignKey("rooms.id", ondelete="CASCADE"), nullable=False)
    slot_id = db.Column(db.Integer, db.ForeignKey("timetable_slots.id", ondelete="CASCADE"), nullable=False)
    presence_date = db.Column(db.Date, nullable=False)
    start_time = db.Column(db.Time, nullable=False)
    end_time = db.Column(db.Time, nullable=False)

    user = db.relationship("User")
    room = db.relationship("Room")
    slot = db.relationship("TimetableSlot")

    __table_args__ = (
        db.UniqueConstraint("user_id", "slot_id", "presence_date", name="uq_presence"),
        # graph_builder.py's core query: "who else was in this room for
        # this slot on this date" — this index is what makes that cheap.
        db.Index("idx_presence_room_slot_date", "room_id", "slot_id", "presence_date"),
        db.Index("idx_presence_user_date", "user_id", "presence_date"),
    )

    def __repr__(self):
        return f"<Presence user={self.user_id} room={self.room_id} date={self.presence_date}>"